bind_to_address "0.0.0.0"  # Permite conexiones desde cualquier dispositivo
port "6600"  # Asegúrate de que este puerto coincide con el de tu configuración de mpc.conf
connection_timeout "5"

music_directory "/storage/642D-151C/Android/data/com.termux/music"
db_file "/storage/642D-151C/Android/data/com.termux/files/home/.cache/mpd/db"
